### ISSUE TITLE
Labs Bug

### ISSUE THREAD

**Issue by Kingpui** [LabScripts/lab-Fields#2]
I can process Poppy even though I don't have one. Of course I can't get any heroin out of it, but maybe the desire for beauty should be fixed

**Comment by LabScripts** [comment]
It plays the animation, after that it checks for the item. I made it that way to avoid too many server callbacks for server-side performance reasons. I will consider changing that tho! :D

**Comment by mikalgoma** [comment]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/classes/player.lua:283: attempt to perform arithmetic on a nil value (field 'weight')
[  script:es_extended] > handler (@lab-Fields/server/main.lua:72)

when process in lab.
