### ISSUE TITLE
SQL Missing?

### ISSUE THREAD

**Issue by Kingpui** [LabScripts/lab-Fields#3]
Hi there,

me again. Could it possibly be that a SQL file with the items that are required is missing? Would you add these too?

**Comment by LabScripts** [comment]
Hey there! The items used, were just added for testing purposes. Each user of this script should configure it to his own drugs, its quite easy 😄

**Comment by Kingpui** [comment]
Wow.
Im so lost. 
Config.Legacy = true 
i dont use Legacy. Turn into off and all work xD
